apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: github-cicd-eks
    app.kubernetes.io/instance: cicd-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: github-cicd-eks
spec:
  selector:
    app: github-cicd-eks
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000